MultipleChoicExam/Models/AddSubject.cs
namespace MultipleChoicExam.Models
{
    public class AddSubject
    {
        public string Search { get; set; }
        public Subject01 Subject { get; set; } = new Subject01();
        public List<Subject01> ListSubject { get; set; } = new List<Subject01>();

    }
}

MultipleChoicExam/Controllers/ManageUserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using MultipleChoicExam.Models;

namespace MultipleChoicExam.Controllers
{
    public class ManageUserController : Controller
    {
        private readonly EFCoreDbContext _dbContext;
        public ManageUserController(EFCoreDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult ManageSubject()
        {
            var subject = new AddSubject { 
                Subject = new Subject01(),
                ListSubject = _dbContext.Subject01.ToList()
            };
            return View(subject);
        }
        [HttpGet]
        public IActionResult AddSubject()
        {
            return View(new Subject01());
        }
        [HttpPost,ActionName("AddSubject")]
        public IActionResult ComfirmAdd(Subject01 sub)
        {
            if(sub == null)
            {
                return View(sub);
            }
            var subject = new Subject01
            {
                SubjectId = sub.SubjectId,
                SubjectName = sub.SubjectName,
                Description = sub.Description,
            };
            if (_dbContext.Subject01.Any(s => s.SubjectId == sub.SubjectId))
            {
                ModelState.AddModelError("", "Môn học này đã tồn tại.");
                return View(sub);
            }
            _dbContext.Subject01.Add(subject);

            _dbContext.SaveChanges();
            return RedirectToAction("ManageSubject");
        }
        [HttpGet]
        public IActionResult EditSubject(string subId)
        {
            var edit = _dbContext.Subject01.FirstOrDefault(s => s.SubjectId == subId);
            if (edit == null)
            {
                return View(new Subject01());
            }
            return View(edit);
        }
        [HttpPost]
        public IActionResult EditSubject(Subject01 mdel)
        {
            var edit = _dbContext.Subject01.FirstOrDefault(s => s.SubjectId == mdel.SubjectId);
            if(edit != null)    
            {
                edit.SubjectName = mdel.SubjectName;
                edit.Description = mdel.Description;
            }
            // lưu lại 
            _dbContext.SaveChanges();
            return RedirectToAction("ManageSubject");
        }
        [HttpPost]
        public IActionResult SearByName(AddSubject add)
        {
            var search = _dbContext.Subject01.FirstOrDefault(s => s.SubjectName == add.Subject.SubjectName);
            if(search == null)
            {
                return View(add);
            }
            return View(search);
        }
        [HttpGet]
        public IActionResult DeleteSubject(string subId) 
        {
            var sub = _dbContext.Subject01.FirstOrDefault(s => s.SubjectId == subId);
            if(sub == null)
            {
                return NotFound();
            }
            return View(sub);
        }
        [HttpPost]
        public IActionResult DeleteSubject(Subject01 model) 
        {
            var delete = _dbContext.Subject01.FirstOrDefault(s => s.SubjectId == model.SubjectId);
            if(delete != null)
            {
                _dbContext.Subject01.Remove(delete);
                _dbContext.SaveChanges();
            }
            return RedirectToAction("ManageSubject");
        }
    }
}

MultipleChoicExam/Views/ManageUser/AddSubject.cshtml
@model MultipleChoicExam.Models.Subject01

<div class="container mt-5">
    <h3>thêm môn thi</h3>
    <div class="container fluid">
        <div class="card">
            <div class="card-body">
                <form asp-controller="ManageUser" asp-action="AddSubject" method="post">
                    <div class="row">
                        <div class="col-sm-4">
                            <label asp-for="SubjectId" class="form-label">Mã môn: </label>
                            <input asp-for="SubjectId" class="form-control" />
                        </div>
                        <div class="col-sm-4">
                            <label asp-for="SubjectName" class="form-label">Tên môn: </label>
                            <input asp-for="SubjectName" class="form-control" />
                        </div>
                        <div class="col-sm-4">
                            <label asp-for="Description" class="form-label">Mô tả: </label>
                            <input asp-for="Description" class="form-control" />
                        </div>
                    </div>
                    <button class="btn btn-success" type="submit">Add</button>
                </form>
            </div>
        </div>
    </div>
</div>

MultipleChoicExam/Views/ManageUser/DeleteSubject.cshtml
@model MultipleChoicExam.Models.Subject01
@{
    ViewData["Title"] = "DeleteSubject";
}

<h1>Bạn có chắc là xóa môn thi này không</h1>
<form asp-controller="ManageUser" asp-action="DeleteSubject" method="post">
    <input type="hidden" asp-for="SubjectId" />
    <button type="submit" class="btn btn-danger">Xác nhận Xóa</button>
    <a asp-action="ManageSubject" class="btn btn-secondary">Hủy</a>
</form>

MultipleChoicExam/Views/ManageUser/EditSubject.cshtml
@model MultipleChoicExam.Models.Subject01

<div class="container mt-3">
    <div class="card card-body">
        <form asp-controller="ManageUser" asp-action="EditSubject" method="post">
            <input asp-for="SubjectId" type="hidden" />
            <div class="row">
                <div class="col-sm-6">
                    <label asp-for="SubjectName" class="form-label">Môn thi</label>
                    <input asp-for="SubjectName" class="form-control" />
                </div>
                <div class="col-sm-6">
                    <label asp-for="Description" class="form-label">mô tả</label>
                    <input asp-for="Description" class="form-control" />
                </div>
            </div>
            <button type="submit" style="align-items: center" class="btn btn-info">Send</button>
        </form>
    </div>
</div>

MultipleChoicExam/Views/ManageUser/ManageSubject.cshtml
@model MultipleChoicExam.Models.AddSubject

@{
    int i
            = 1;
}
<div class="container mt-2">
    <h3 class="text-center">Thông tin môn thi</h3>
</div>
<div class="d-flex align-items-center mb-3 mt-2">
    <a asp-controller="ManageUser" asp-action="AddSubject" class="btn btn-outline-info">Thêm </a>
    <!-- Search ở cuối -->
        <form class="d-flex ms-auto gap-2" asp-controller="ManageUser" asp-action="SearByName" method="post">
            <input type="text" asp-for="Subject.SubjectName" class="form-control" placeholder="Search Name">
            <button class="btn btn-primary me-2">Search</button>
        </form>
</div>
<div class="card">
    <div class="card-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Mã Môn</th>
                    <th>Tên Môn</th>
                    <th>Mô tả</th>
                    <th>Hành đ</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model.ListSubject)
                {
                    <tr>
                        <td>
                           @i
                        </td>
                        <td>@item.SubjectId </td>
                        <td>@item.SubjectName</td>
                        <td>@item.Description</td>
                        <td>
                            <a asp-controller="ManageUser" asp-action="EditSubject" asp-route-subId="@item.SubjectId" class="btn btn-success">Sửa</a>
                            <a asp-controller="ManageUser" asp-action="DeleteSubject" asp-route-subId="@item.SubjectId" class="btn btn-success">Xóa</a>
                        </td>
                    </tr>
                    i++;
                }
            </tbody>
        </table>
    </div>
</div>

MultipleChoicExam/Views/ManageUser/ManageUser.cshtml
@{
    ViewData["Title"] = "ManageUser";
}

<h1>ManageUser</h1>

MultipleChoicExam/Views/ManageUser/SearByName.cshtml
@model MultipleChoicExam.Models.Subject01

<h1>SearByName</h1>
<p>@Model.SubjectName</p>
<p>@Model.Description</p>